#!/usr/bin/env sh

#
# Copyright 2015-the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle
#
#   https://github.com/gradle/gradle/blob/HEAD/src/bootstrap/src/main/unix/gradlew
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD to a smaller value
if [ -n "$MAX_FD" ] ; then
  DESCRIPTOR_LIMIT="$MAX_FD"
else
  DESCRIPTOR_LIMIT=`ulimit -H -n 2>/dev/null`
  if [ $? -eq 0 ] ; then
    if [ -n "$DESCRIPTOR_LIMIT" ] && [ "$DESCRIPTOR_LIMIT" -eq "$DESCRIPTOR_LIMIT" ] 2>/dev/null ; then
      MAX_FD="$DESCRIPTOR_LIMIT"
    else
      MAX_FD="1024"
    fi
  else
    MAX_FD="64"
  fi
  ulimit -n "$MAX_FD" 2>/dev/null
fi

cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* | MSYS* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the java executable
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || {
        echo >&2 "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo >&2 "Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
        exit 1
    }
fi

# Increase the maximum file descriptor limit if we can
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -n 65536 2>/dev/null`
    if [ $? -eq 0 ] ; then
        if [ -n "$MAX_FD" ] ; then
            if [ "$MAX_FD" -gt "$MAX_FD_LIMIT" ] ; then
                MAX_FD="$MAX_FD_LIMIT"
            fi
        else
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n "$MAX_FD" 2>/dev/null
    fi
fi

# For Cygwin, switch paths to Windows format before running java
if [ "$cygwin" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    JAVACMD=`cygpath --unix "$JAVACMD"`
    save_IFS=$IFS
    IFS=:
    class_path_entries=($CLASSPATH)
    IFS=$save_IFS
    CLASSPATH=""
    for i in "${class_path_entries[@]}" ; do
        cs_entry=`cygpath --path --mixed "$i"`
        if [ -n "$CLASSPATH" ] ; then
            CLASSPATH="$CLASSPATH:$cs_entry"
        else
            CLASSPATH="$cs_entry"
        fi
    done
    unset class_path_entries
fi

# For Msys, switch paths to Windows format before running java
if [ "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    JAVACMD=`cygpath --mixed "$JAVACMD"`
    class_path_entries=($CLASSPATH)
    CLASSPATH=""
    for i in "${class_path_entries[@]}" ; do
        cs_entry=`cygpath --mixed "$i"`
        if [ -n "$CLASSPATH" ] ; then
            CLASSPATH="$CLASSPATH;$cs_entry"
        else
            CLASSPATH="$cs_entry"
        fi
    done
    unset class_path_entries
fi

# Escape all characters using double quotes
# shellcheck disable=SC2086
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
