
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.system.cedd1744'
    compileSdk 34
    defaultConfig {
        applicationId 'com.system.cedd1744'
        minSdk 28
        targetSdk 34
        versionCode 894
        versionName '14.2.1'
        
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.core:core-ktx:1.12.0'
}
