name: Generate Project Files
on: [push]
jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Run Generator
          run: python generate_project.py
        - name: Commit and Push Generated Files
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Auto-generate project files"

